# Generated by Django 5.2 on 2026-04-20 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('moysklad_id', models.CharField(blank=True, default='', max_length=100)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('full_name', models.CharField(blank=True, default='', max_length=300)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], default='', max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debt_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('state', models.CharField(choices=[('none', 'None'), ('awaiting_phone', 'Awaiting Phone'), ('awaiting_name', 'Awaiting Name'), ('awaiting_region', 'Awaiting Region'), ('awaiting_gender', 'Awaiting Gender'), ('awaiting_birthdate', 'Awaiting Birthdate'), ('awaiting_new_name', 'Awaiting New Name'), ('awaiting_new_birthdate', 'Awaiting New Birthdate'), ('awaiting_report_period', 'Awaiting Report Period'), ('awaiting_store_photo', 'Awaiting Store Photo'), ('awaiting_store_text', 'Awaiting Store Text'), ('awaiting_supplier_id', 'Awaiting Supplier ID'), ('awaiting_cashout_client', 'Awaiting Cashout Client'), ('awaiting_cashout_amount', 'Awaiting Cashout Amount'), ('awaiting_debt_client', 'Awaiting Debt Client'), ('awaiting_debt_amount', 'Awaiting Debt Amount')], default='none', max_length=30)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_groups', models.JSONField(blank=True, default=list)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=300)),
                ('supplier_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file_id', models.CharField(blank=True, default='', max_length=500)),
                ('text', models.TextField(blank=True, default='')),
                ('contact_info', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Info',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Продажа'), ('return', 'Возврат'), ('bonus_add', 'Начисление бонуса'), ('bonus_deduct', 'Списание бонуса'), ('payment_in', 'Входящий платеж'), ('payment_out', 'Исходящий платеж'), ('cash_in', 'Приходный ордер'), ('cash_out', 'Расходный ордер')], max_length=20)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('document_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debt_change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('moysklad_entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bot.customer')),
            ],
            options={
                'ordering': ['-document_date'],
            },
        ),
    ]
