# Generated by Django 5.2 on 2026-04-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pending_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
