# Generated by Django 5.2 on 2026-04-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_add_pending_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bonus_bearing_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
